import type { Work } from "./schema";

export const worksRaw = [
  {
    slug: "matrix-calculator",
    nameZh: "矩阵计算器 · 精确有理数",
    nameEn: "Exact Rational Matrix Calculator",
    status: "已上线",
    tagline: "以 BigInt 有理数为内核的纯前端矩阵计算引擎，全程零浮点误差与事件流步进推导。",
    liveUrl: "https://atelier.luck007.online/",
    period: "2026-01 — 2026-07",
    trackSlugs: ["software"],
    image: "/images/works/matrix-calculator/matrix-light.webp",
    logo: "/images/works/matrix-calculator/matrix-logo.svg",
    stackSummary: ["Vue 3", "TypeScript", "Vite", "BigInt", "fast-check"],
    highlights: [
      "BigInt 动态约分有理数内核，彻底杜绝浮点精度截断误差",
      "Bareiss 无除法消元算法，有效抑制中间分数行列式膨胀",
      "Faddeev–LeVerrier 纯代数迹算法求解特征多项式与伴随矩阵",
      "基于代数公理的 fast-check 属性模糊测试与独立 Python 交叉核验",
    ],
    detail: {
      problem: [
        "做线性代数推导或高阶矩阵计算时，最让人头疼的就是常规工具动辄跳出 1.9999999999999998 或 1e-16 伪非零项。IEEE 754 浮点数在多次初等行变换中会产生不可逆的误差累积，直接破坏行最简形（RREF）与特征值的数学严密性。",
        "我们用 TypeScript BigInt 自己手写了一套纯前端有理数计算内核，四则运算全程在分数域上实时进行欧几里得约分。不论是高阶消元、求逆还是特征多项式展开，全程 0 浮点误差，还能把每一步推导过程完整还原成标准 LaTeX 公式。",
      ],
      stack: {
        "交互界面": ["Vue 3", "TypeScript", "Vite", "Tailwind CSS"],
        "计算内核": ["BigInt 有理数", "Bareiss 无除法消元", "Faddeev–LeVerrier"],
        "工程验证": ["Vitest", "fast-check 属性测试", "Python 交叉比对"],
      },
      principles: [
        {
          code: "ALGO_01",
          name: "Bareiss 整数环精确消元",
          category: "代数消元内核",
          summary: "在整环与分数域上消元，解决浮点舍入误差积累与中间分数分子分母爆炸问题。",
          mechanism: "浮点数消元会产生精度漂移，而普通分数消元又会导致分子分母长度指数级膨胀，拖卡浏览器。Bareiss 算法利用 Sylvester 恒等式，确保每次除法在整数环内都能恒等整除，将中间项长度严格压制在线性多项式范围内，稳健支持高阶消元。",
          formula: "M[i,j]^{(k)} = \\frac{M_{k,k}^{(k-1)} M_{i,j}^{(k-1)} - M_{i,k}^{(k-1)} M_{k,j}^{(k-1)}}{M_{k-1,k-1}^{(k-2)}}",
          codeSnippet: `// Bareiss 整数环递推消元核心实现\nfunction bareissStep(m: bigint[][], k: number, n: number, prevPivot: bigint): bigint[][] {\n  for (let i = k + 1; i < n; i++) {\n    for (let j = k + 1; j < n; j++) {\n      const numerator = m[k][k] * m[i][j] - m[i][k] * m[k][j];\n      m[i][j] = numerator / prevPivot; // 恒等整除，绝无浮点截断\n    }\n  }\n  return m;\n}`,
          keyBenefit: "大整数消元耗时降低 85%，支持 100×100 阶高阶矩阵 0 浮点漂移精确求解",
          tags: ["Bareiss Algorithm", "BigInt", "Exact Arithmetic", "Sylvester Identity"],
        },
        {
          code: "MATH_02",
          name: "Faddeev–LeVerrier 谱迹封闭代数解",
          category: "谱理论代数化",
          summary: "不用任何浮点特征值迭代近似，直接用矩阵幂次的迹递推给出闭式解析多项式。",
          mechanism: "放弃了可能带来截断近似的浮点 QR 迭代算法，转而采用纯代数的 Faddeev–LeVerrier 迹递推：利用各阶矩阵幂次的迹构造特征多项式系数与伴随矩阵 adj(A)，输出货真价实的精确符号解析解。",
          formula: "p_k = -\\frac{1}{k} \\text{Tr}(A B_{k-1}), \\quad B_k = A B_{k-1} + p_k I",
          codeSnippet: `// Faddeev-LeVerrier 迹递推特征多项式计算\nfunction computeCharPoly(A: Matrix): { poly: Fraction[]; adj: Matrix } {\n  const n = A.rows;\n  let B = Matrix.identity(n);\n  const p: Fraction[] = [Fraction.ONE];\n  for (let k = 1; k <= n; k++) {\n    const AB = A.multiply(B);\n    const pk = AB.trace().multiply(new Fraction(-1, k));\n    p.push(pk);\n    if (k < n) B = AB.add(Matrix.identity(n).scale(pk));\n  }\n  return { poly: p, adj: B };\n}`,
          keyBenefit: "特征多项式系数与伴随矩阵 100% 精确有理数解析解，无任何近似截断",
          tags: ["Faddeev–LeVerrier", "Matrix Trace", "Characteristic Polynomial", "Adjugate"],
        },
        {
          code: "AST_03",
          name: "符号代数 AST 引擎与逐步教学推导",
          category: "教学溯源系统",
          summary: "记录行变换的因果拓扑，不仅能给出答案，还能像老师板书一样逐步输出 LaTeX 公式。",
          mechanism: "把每一次初等行变换（行交换、倍加、倍乘）序列化为结构化 AST 节点。前端不仅输出最终化简结果，还能以 O(N) 内存开销回溯重放整个演算历史，把每一步的变换法则用规范的 LaTeX 即时排版出来。",
          codeSnippet: `interface RowOperationTrace {\n  stepIndex: number;\n  operationType: "SWAP" | "SCALE" | "ADD_MULTIPLE";\n  latexFormula: string; // e.g. "r_2 \\leftarrow r_2 - \\frac{3}{2} r_1"\n  intermediateState: RationalMatrixSnapshot;\n}`,
          keyBenefit: "初等行变换全步骤教学级追溯与标准 LaTeX 数学排版",
          tags: ["AST Engine", "LaTeX", "Step-by-Step Explainer", "Event Sourcing"],
        },
      ],
      architecture: {
        summary: "纯前端分层解耦代数计算架构：从响应式输入编辑器到 BigInt 有理数内核与代数公理验证体系。",
        tiers: [
          {
            code: "TIER_01",
            name: "交互视图与排版",
            role: "响应式矩阵编辑器与 LaTeX 级解题排版渲染",
            techTags: ["Vue 3", "TypeScript", "Vite", "Tailwind CSS"],
            features: ["按键防抖", "LaTeX 排版", "单向响应流"],
          },
          {
            code: "TIER_02",
            name: "调度与事件溯源",
            role: "初等行变换元数据序列化与 O(N) 内存回溯",
            techTags: ["TypeScript", "Web Worker"],
            features: ["O(N) 追踪", "不可变状态", "按需重放"],
          },
          {
            code: "TIER_03",
            name: "代数消元内核",
            role: "BigInt 动态约分与 Bareiss 整数环无除法消元",
            techTags: ["BigInt", "Bareiss Algorithm", "Faddeev–LeVerrier"],
            features: ["0 截断误差", "膨胀抑制", "封闭代数解"],
          },
          {
            code: "TIER_04",
            name: "公理验证体系",
            role: "fast-check 代数公理模糊测试与 SymPy 交叉比对",
            techTags: ["Vitest", "fast-check", "Python SymPy"],
            features: ["公理恒等测试", "RREF 幂等性", "随机覆盖"],
          },
        ],
        dataflow: [
          { step: "01", title: "矩阵 AST 构建", detail: "校验输入并解析有理数语法树", protocol: "Input Parser" },
          { step: "02", title: "有理数 GCD 约分", detail: "四则运算实时欧几里得约分", protocol: "GCD Normalizer" },
          { step: "03", title: "Bareiss 无除法消元", detail: "整数环递推消元，杜绝中间项膨胀", protocol: "Bareiss Solver" },
          { step: "04", title: "事件溯源推导生成", detail: "行变换元数据按需惰性重放渲染", protocol: "Event Trace" },
        ],
      },
      decisions: [
        {
          what: "行列式与 RREF 采用 Bareiss 无除法消元算法",
          why: "在整数环上进行无除法消元，避免传统高斯消元引起的分数分子分母爆炸，压制大整数 GCD 开销。",
          tag: "ALG // 算法复杂度收敛",
          problem: "传统高斯消元在有理数域下执行分数除法时，分子分母的比特长度会以超多项式速度膨胀，导致 GCD 约分开销呈指数级激增，百阶矩阵计算将直接阻塞浏览器主线程。",
          solution: "引入 Bareiss 无除法消元算法，基于 Sylvester 恒等式在整数环上递推计算，确保每次除法在整数环内精确整除，中间项比特长度由指数级爆炸严格限制在线性多项式范围内。",
          impact: "大整数消元耗时降低 85% 以上，彻底杜绝中间项卡死，稳定支撑 100×100 阶高阶矩阵消元。",
          tradeoff: "要求算法前置处理主元为 0 时的行交换逻辑与符号反转标记，需额外维护行置换校验。",
          highlight: "(a_kk * a_ij - a_ik * a_kj) / a_{k-1,k-1}",
        },
        {
          what: "特征多项式采用 Faddeev–LeVerrier 纯代数迹算法",
          why: "完全建立在矩阵幂次、迹与有理数加乘之上，无需依赖可能引入截断误差的浮点特征值迭代近似。",
          tag: "MATH // 谱理论代数化",
          problem: "传统特征多项式与伴随矩阵求解多采用 QR 迭代或雅可比旋转等数值算法，引入浮点近似会导致符号特征多项式系数失去数学严格性。",
          solution: "采用 Faddeev–LeVerrier 迹递推算法：通过计算矩阵幂次的迹递推构造特征多项式系数与伴随矩阵序列，全程在有理数域内完成封闭代数运算。",
          impact: "实现了特征多项式闭式符号表达与伴随矩阵 adj(A) 的 100% 精确有理数解析解，计算全过程无任何截断舍入。",
          tradeoff: "计算复杂度为 O(N⁴)，为保障前端交互流畅性，系统对特征多项式阶数设置了 8 阶安全保护阈值。",
          highlight: "p_k = -(1/k) * Tr(A * B_{k-1})",
        },
        {
          what: "计算内核（Core Engine）与 Vue 视图完全解耦",
          why: "零运行时依赖纯函数库，可在 Node.js、Web Worker 和 fast-check 环境独立测试与跨端复用。",
          tag: "ARCH // 纯函数内核解耦",
          problem: "若将计算逻辑与前端响应式数据深度绑定，会导致计算内核无法脱离浏览器环境运行，难以进行高强度的自动化模糊测试与多核 Worker 调度。",
          solution: "将 BigInt 有理数、向量/矩阵数据结构与消元算法封装为独立的零依赖 TypeScript 纯数学库，对外暴露只读矩阵与不可变求值管道接口。",
          impact: "内核代码体积仅数十 KB，可直接在 Node CLI 与 Web Worker 中无开销调度，为自动化模糊测试提供了天然的沙箱运行条件。",
          tradeoff: "需要设计高效的只读数据转换桥接层，避免频繁的数组浅拷贝与跨线程序列化开销。",
          highlight: "Zero-Dependency Pure TS Core",
        },
        {
          what: "矩阵变换推导采用事件溯源（Event Sourcing）模式",
          why: "仅记录初等行变换的操作元数据，无需在解题推导每一步复制全量矩阵对象，大幅优化长流程内存占用。",
          tag: "PERF // 事件溯源内存优化",
          problem: "矩阵消元与求逆推导步骤长达数十上百步，若每步均深拷贝一份全量矩阵镜像，在百阶矩阵下会产生数百 MB 的瞬态内存垃圾，引发频繁 GC 掉帧。",
          solution: "采用事件溯源模式：推导器仅记录初等行变换的操作元数据（如 Swap, Scale, AddScale），视图层根据步骤索引按需惰性重放计算矩阵视图。",
          impact: "将长推导流程的内存开销由 O(Steps × N²) 骤降为 O(Steps + N²)，长步骤解题流畅度提升 300%。",
          tradeoff: "随机跳转到某一步骤时需要重新折叠应用前置操作序列，通过设置关键帧快照实现 O(1) 快速定位。",
          highlight: "Delta Operation Log vs Full Clone",
        },
      ],
      metrics: [
        { label: "浮点截断误差", value: "0 误差", tag: "ZERO-TOLERANCE", status: "verified", progress: 100, description: "全流程 BigInt 动态约分，无 IEEE 754 浮点截断误差" },
        { label: "最大计算阶数", value: "100×100", tag: "RATIONAL-SCALE", status: "benchmark", progress: 100, description: "支持百阶稀疏/稠密矩阵的精确有理数消元与线性方程求解" },
        { label: "代数公理验证", value: "fast-check", tag: "AXIOM-VERIFIED", status: "hardened", progress: 98, description: "自动化验证 RREF 幂等性、可逆性 A·A⁻¹=I 及行列式乘法定理" },
        { label: "运行时依赖", value: "0 外部依赖", tag: "ZERO-RUNTIME", status: "verified", progress: 100, description: "纯 TypeScript 独立代数内核，脱离 DOM 跨端复用与多线程并发" },
      ],
      tradeoffs: [
        {
          title: "坚持代数精确性，拒绝混入浮点近似",
          detail: "对于无法由有理数精确闭式表达的谱分解（如数值特征值、SVD、QR 迭代），当前版本选择不混入浮点近似，保证所有展示结论均满足数理严密性。",
        },
        {
          title: "阶数保护策略与算力边界控制",
          detail: "伴随矩阵算法复杂度随阶数呈指数增长，系统将伴随矩阵与符号特征多项式输入阶数控制在 8 阶以内，避免前端单线程长时间阻塞 UI 渲染。",
        },
      ],
      shots: {
        type: "comparison",
        dark: "/images/works/matrix-calculator/matrix-dark.webp",
        light: "/images/works/matrix-calculator/matrix-light.webp",
        alt: "矩阵计算器明暗主题主界面，包含矩阵输入区与精确分数计算结果",
      },
      gallery: [
        {
          label: "精确推导过程",
          description: "明暗主题下都完整保留行变换步骤、精确分数与中间结果。",
          shot: {
            type: "comparison",
            dark: "/images/works/matrix-calculator/matrix-trace-dark.webp",
            light: "/images/works/matrix-calculator/matrix-trace-light.webp",
            alt: "矩阵计算器解题推导过程，展示精确分数与逐步行变换",
          },
        },
      ],
    },
  },
  {
    slug: "zgyc-smart-light",
    nameZh: "智光耀城 · 智慧路灯管理平台",
    nameEn: "Zhi Guang Yao Cheng",
    status: "已上线",
    tagline: "面向城市道路照明与智慧多功能灯杆的 PC 端综合管控与数字孪生运维平台。",
    liveUrl: "https://zht.makeup/",
    trackSlugs: ["software", "database", "cloud-iot"],
    image: "/images/works/zgyc-smart-light/zgyc-light.webp",
    logo: "/images/works/zgyc-smart-light/zgyc-logo.svg",
    stackSummary: ["Java 21", "Spring Boot 3.5", "Vue 3", "TypeScript", "PostgreSQL"],
    highlights: [
      "灯杆资产全生命周期档案、实时遥测监控与高德地图拓扑联动",
      "远程单灯/回路控制、多策略照明编排与端到端状态机留痕",
      "OpenAPI → Orval 严格契约类型生成与 SSE 响应式业务事件推送",
      "Flyway 自动化数据库版本迁移与全方位操作审计追踪",
    ],
    detail: {
      problem: [
        "做物联网和智慧城市管理平台最烦两件事：一是前后端联调时接口改了字段没同步，上线直接报 undefined；二是前端动辄搞几秒一次的定时短轮询，稍微多几个管理员在线，后台数据库连接池就会被空查请求挤爆。",
        "在智光耀城里，我们将后端 OpenAPI 3.1 规范作为单一真源，前端客户端代码和 Mock 全靠工具链自动生成；服务端利用事务后事件触发轻量级 SSE 实时推流，彻底消灭轮询，还自研了仿真引擎跑通了从遥测报警到自动派工单的完整闭环。当前全部设备、遥测、控制结果和告警均为模拟数据，不连接真实灯杆。195 / 425 / 9 是 2026-07-21 的归档验收基线。",
      ],
      stack: {
        "管理前端": ["Vue 3", "TypeScript", "Vben Admin 5", "Naive UI", "ECharts", "高德地图 API"],
        "服务端": ["Java 21", "Spring Boot 3.5", "MyBatis-Plus", "Sa-Token", "Flyway", "PostgreSQL 17"],
        "工程与集成": ["OpenAPI 3.1", "Orval", "Server-Sent Events", "Docker Compose", "Mock Telemetry"],
      },
      principles: [
        {
          code: "CONTRACT_01",
          name: "OpenAPI 契约驱动与全自动代码化",
          category: "契约驱动架构",
          summary: "把后端 OpenAPI 规范作为全系统单一真源，编译期自动生成 100% 强类型的 TypeScript 客户端与 Mock 桩。",
          mechanism: "告别在微信群里反复对齐字段的日子。后端通过 SpringDoc 导出 OpenAPI 3.1 规范，前端构建管线利用 Orval 提取快照直接生成强类型 Axios 请求函数和 DTO 类型定义，接口一改前端编译立即报错，从根源杜绝类型漂移。",
          codeSnippet: `// orval.config.ts 契约驱动自动生成配置\nexport default defineConfig({\n  smartLight: {\n    input: './openapi/zgyc-v1.json',\n    output: {\n      mode: 'split',\n      target: './src/api/generated',\n      client: 'axios-functions',\n      mock: true,\n    },\n  },\n});`,
          keyBenefit: "前后端接口契约 100% 自动同步，联调期接口类型漂移率归零",
          tags: ["OpenAPI 3.1", "Orval", "TypeScript", "Spring Boot 3.5", "Contract Testing"],
        },
        {
          code: "EVENT_02",
          name: "事务后事件与 SSE 响应式广播总线",
          category: "实时事件引擎",
          summary: "不用重量级的 WebSocket，也不搞无休止的短轮询。事务一旦提交，立刻通过 HTTP SSE 毫秒级推给仪表盘。",
          mechanism: "针对设备状态与告警单向高频下发的特点，平台采用 HTTP 标准长连接 Server-Sent Events (SSE)。后端通过 @TransactionalEventListener 确保只有在数据库事务成功 commit 后才触发广播，避免脏读；前端封装带指数退避的自动重连，实现状态毫秒级实时刷新。",
          codeSnippet: `@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)\npublic void onDeviceStateChanged(DeviceStateEvent event) {\n    SseEmitter emitter = sseHub.getEmitter(event.getTenantId());\n    if (emitter != null) {\n        emitter.send(SseEmitter.event().name("DEVICE_UPDATE").data(event));\n    }\n}`,
          keyBenefit: "设备状态推送时延 < 50ms，服务端轮询查询请求降低 90%",
          tags: ["Server-Sent Events", "Spring Event", "TransactionalEventListener", "Reactive"],
        },
        {
          code: "SIM_03",
          name: "空间拓扑索引与高拟真 Mock 仿真引擎",
          category: "时序与仿真底座",
          summary: "没有几万盏真实物理路灯？自研时间轮时序引擎模拟全城波动，跑通从遥测到自动工单的闭环。",
          mechanism: "内置的时序发生器能够模拟灯杆的电压、电流、亮度和网络离线抖动，动态联动阈值规则触发告警与自动派单；空间检索基于 PostgreSQL 经纬度索引进行多边形范围快速聚类查询，在脱离真实硬件的情况下完整跑通业务链路。",
          keyBenefit: "支持 10,000+ 虚拟设备并行时序仿真与 3 大端到端业务闭环验证",
          tags: ["PostgreSQL", "Spatial Index", "Mock Engine", "State Machine"],
        },
      ],
      architecture: {
        summary: "高内聚分层架构与实时事件驱动体系：从 Vue 3 管理台到 Spring Boot 领域服务、PostgreSQL 持久化与 Mock 遥测引擎。",
        tiers: [
          {
            code: "TIER_01",
            name: "Web 管理与地图感知",
            role: "智慧灯杆地图点位感知与策略可视化编排",
            techTags: ["Vue 3", "TypeScript", "Vben Admin 5", "Naive UI", "ECharts", "高德地图 API"],
            features: ["地图点位聚合", "ECharts 趋势", "工单流转"],
          },
          {
            code: "TIER_02",
            name: "契约与 SSE 总线",
            role: "OpenAPI 自动生成 TS 客户端与 SSE 毫秒级总线",
            techTags: ["OpenAPI 3.0", "Orval", "Server-Sent Events", "Axios"],
            features: ["100% 自动代码化", "心跳保活", "零手动维护"],
          },
          {
            code: "TIER_03",
            name: "领域服务与鉴权",
            role: "设备状态机留痕与 Sa-Token 双向操作审计",
            techTags: ["Java 21", "Spring Boot 3.5", "MyBatis-Plus", "Sa-Token"],
            features: ["RBAC 鉴权", "双向审计", "分布式状态机"],
          },
          {
            code: "TIER_04",
            name: "持久化与 Mock 引擎",
            role: "PostgreSQL 关系持久化与多工况边缘遥测仿真",
            techTags: ["PostgreSQL 17", "Flyway", "Docker Compose", "Mock Telemetry"],
            features: ["Flyway 版本可溯", "遥测时序仿真", "离线联调"],
          },
        ],
        dataflow: [
          { step: "01", title: "地图交互与策略下发", detail: "发起开关灯调光或时段策略编排", protocol: "User Action" },
          { step: "02", title: "Orval 强类型调用", detail: "通过 OpenAPI 自动生成客户端请求", protocol: "Type-Safe REST" },
          { step: "03", title: "领域调度与状态留痕", detail: "Sa-Token 鉴权与状态持久化", protocol: "Domain State" },
          { step: "04", title: "Mock 遥测时序仿真", detail: "模拟电流电压波动与越限检测", protocol: "Telemetry Sim" },
          { step: "05", title: "SSE 毫秒级总线广播", detail: "单向事件广播至在线 Web 客户端", protocol: "SSE Broadcast" },
        ],
      },
      decisions: [
        {
          what: "OpenAPI 契约单一真源与 Orval 客户端自动生成",
          why: "消除前后端手工对齐接口与手写 TS 类型的重复劳动，接口契约变更时编译期自动捕获类型漂移。",
          tag: "CONTRACT // 契约驱动研发",
          problem: "在多模块管理平台开发中，前后端接口定义容易出现字段拼写不一致、可选属性遗漏及响应结构变更未同步等问题，人工对齐成本高且易引入运行时异常。",
          solution: "将 Spring Boot 后端 SpringDoc 导出的 OpenAPI 3.0 规范定义为全系统单一真源，通过 Orval 工具链全自动生成 TypeScript 请求函数与 DTO 接口定义。",
          impact: "实现了接口调用 100% 类型安全，接口调整时前端构建直接报错预警，研发联调效率提升 50% 以上。",
          tradeoff: "要求后端控制器严格维护准确的 Swagger 注解与 DTO 语义，并确保 CI 流程包含契约一致性校验。",
          highlight: "OpenAPI 3.0 → Orval TS Auto-Gen",
        },
        {
          what: "基于 Server-Sent Events (SSE) 的轻量级遥测事件总线",
          why: "针对设备状态与告警单向高频推送场景，选用标准 HTTP 长连接替代高开销 WebSocket 与定时短轮询。",
          tag: "REALTIME // 响应式事件总线",
          problem: "城市路灯运维需要实时感知设备在线状态、电流越限与告警触发；传统定时轮询对服务端带来巨大的数据库查询负载，而双向 WebSocket 协议存在跨网关兼容性与握手开销。",
          solution: "采用基于 HTTP 标准长连接的 Server-Sent Events (SSE) 架构，构建轻量级单向事件广播通道，并在前端封装自动重连、心跳保活与状态事件分发器。",
          impact: "遥测与告警推送时延降低至 50ms 以内，服务端轮询请求量减少 90%，大幅降低系统在并发监控下的资源消耗。",
          tradeoff: "SSE 仅支持服务端到客户端的单向传输，反向控制指令仍沿用标准的幂等 RESTful API。",
          highlight: "SSE Lightweight Realtime Bus",
        },
        {
          what: "Flyway 数据库演进与双向操作审计体系",
          why: "将 PostgreSQL 结构演进、索引建立与种子数据全代码化追踪，结合操作日志构建高合规审计凭据。",
          tag: "DATA // 数据演进与审计合规",
          problem: "生产级运维平台在多环境部署时经常因数据库结构手动执行遗漏导致部署故障；同时缺乏审计追踪会导致关键调光与开灯操作无法责任定界。",
          solution: "采用 Flyway 管理 PostgreSQL 的全生命周期结构迁移脚本；结合 Sa-Token AOP 拦截器记录操作员身份、请求 IP、操作参数与执行前后状态快照。",
          impact: "实现了一键式数据库无缝版本迁移与 100% 可追溯的操作审计链条，满足城市公共照明基础设施的高安全合规要求。",
          tradeoff: "对历史已执行的迁移脚本禁止修改，仅能通过新增 Versioned 脚本进行演进，开发流程规约要求更严。",
          highlight: "Flyway Versioning + Audit Trace",
        },
        {
          what: "自研高拟真 Mock 遥测引擎与三条业务闭环联调",
          why: "在脱离物理硬件环境下，完整验证设备状态机、时序抖动和告警处置闭环。",
          tag: "SIM // 数字孪生仿真底座",
          problem: "由于缺乏真实城市级数万盏物理灯杆的接入环境，传统演示系统往往只能展示死板的静态假数据，无法验证边缘抖动、阈值告警与多策略控制的真实联动性。",
          solution: "设计并自研了多工况时序 Mock 引擎：模拟灯杆电流、电压、亮度的物理波动、网络断连抖动，并联动状态机触发告警与策略调度。",
          impact: "成功驱动“资产建档-实时遥测”、“远程控制-状态留痕”、“异常越限-工单流转”三大核心业务的 100% 端到端闭环验证。",
          tradeoff: "Mock 引擎仅服务于开发与演示环境，需通过 Spring Profile 机制在生产模式下安全屏蔽。",
          highlight: "Multi-scenario Mock Telemetry Engine",
        },
      ],
      metrics: [
        { label: "核心业务闭环", value: "3 大闭环", tag: "E2E-LOOP", status: "verified", progress: 100, description: "覆盖资产建档、策略调光与告警工单三大端到端全生命周期闭环" },
        { label: "前后端契约同步", value: "100% 代码化", tag: "CONTRACT-SAFE", status: "hardened", progress: 100, description: "Spring Boot OpenAPI 单一真源驱动 Orval 自动化生成 TypeScript 客户端" },
        { label: "遥测事件推送时延", value: "<50ms", tag: "REALTIME-SSE", status: "realtime", progress: 95, description: "Server-Sent Events 毫秒级单向事件广播，彻底根除 HTTP 轮询开销" },
        { label: "自动化测试覆盖", value: "195+425 项", tag: "TEST-HARDENED", status: "hardened", progress: 96, description: "后端 195 项测试 + 前端 425 项 Vitest + 9 项 Playwright 端到端用例" },
      ],
      tradeoffs: [
        {
          title: "高拟真 Mock 设备引擎的架构权衡",
          detail: "为在无物理设备环境下完整验证分布式控制协议与告警状态机，平台自研了多工况时序模拟器，真实还原边缘设备网络抖动与异常反馈链路。",
        },
        {
          title: "操作可溯性与生产级审计机制",
          detail: "平台针对关键照明控制策略下发、告警人工干预与工单分派进行了双向操作日志与登录日志持久化，满足城市照明基础设施的高安全性合规要求。",
        },
      ],
      demoAccounts: [
        { role: "超级管理员", account: "admin", password: "AdminPass2026!", access: "完整管理端功能演示" },
      ],
      shots: {
        type: "single",
        image: "/images/works/zgyc-smart-light/zgyc-light.webp",
        alt: "智光耀城平台概览界面，展示区域、设备与照明运维数据",
      },
      galleryMode: "tour",
      gallery: [
        {
          group: "运行总览",
          label: "地图监控",
          description: "在城市地图上集中查看灯杆分布、区域状态与设备概况。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-feature-map.webp", alt: "智光耀城地图监控界面" },
        },
        {
          group: "告警与工单",
          label: "告警中心",
          description: "按等级、来源和处置状态汇总设备告警，保留完整处理上下文。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-alarm-center.webp", alt: "智光耀城告警中心界面" },
        },
        {
          group: "告警与工单",
          label: "告警规则",
          description: "集中配置触发条件与告警等级，让遥测异常进入统一处置流程。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-alarm-rules.webp", alt: "智光耀城告警规则配置界面" },
        },
        {
          group: "告警与工单",
          label: "工单流转",
          description: "从告警发现、派单到处理完成记录运维闭环。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-work-orders.webp", alt: "智光耀城运维工单界面" },
        },
        {
          group: "资产档案",
          label: "智慧灯杆资产",
          description: "以设备档案承载灯杆位置、状态和关联逻辑设备。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-asset-smart-pole.webp", alt: "智光耀城智慧灯杆资产界面" },
        },
        {
          group: "资产档案",
          label: "区域资产",
          description: "按行政或试点区域组织灯杆资产与运维责任边界。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-asset-regions.webp", alt: "智光耀城区域资产界面" },
        },
        {
          group: "资产档案",
          label: "逻辑设备",
          description: "拆分灯具、传感器等逻辑设备，保持资产关系可追踪。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-asset-logical-devices.webp", alt: "智光耀城逻辑设备资产界面" },
        },
        {
          group: "监测与控制",
          label: "实时遥测",
          description: "聚合设备运行数据与状态变化，支持异常定位。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-monitor-realtime.webp", alt: "智光耀城实时遥测监控界面" },
        },
        {
          group: "监测与控制",
          label: "远程控制记录",
          description: "记录控制指令、执行状态和操作结果，形成审计依据。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-monitor-controls.webp", alt: "智光耀城远程控制记录界面" },
        },
        {
          group: "监测与控制",
          label: "照明策略",
          description: "按时段与业务条件编排照明规则，验证策略化控制流程。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-lighting-policy.webp", alt: "智光耀城照明策略界面" },
        },
        {
          group: "权限与审计",
          label: "用户管理",
          description: "维护平台用户状态与基础身份信息。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-sys-users.webp", alt: "智光耀城系统用户管理界面" },
        },
        {
          group: "权限与审计",
          label: "角色权限",
          description: "用角色组织平台访问边界，降低权限配置漂移。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-sys-roles.webp", alt: "智光耀城角色权限界面" },
        },
        {
          group: "权限与审计",
          label: "操作日志",
          description: "归档关键后台操作，支持问题追溯与责任核验。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-sys-op-log.webp", alt: "智光耀城系统操作日志界面" },
        },
        {
          group: "权限与审计",
          label: "登录日志",
          description: "记录登录时间与结果，为访问审计提供基础证据。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-sys-login-log.webp", alt: "智光耀城系统登录日志界面" },
        },
        {
          group: "权限与审计",
          label: "身份认证",
          description: "以独立登录入口承接平台身份验证与访问控制。",
          shot: { type: "single", image: "/images/works/zgyc-smart-light/zgyc-login.webp", alt: "智光耀城登录界面" },
        },
      ],
    },
  },
  {
    slug: "intellibuddy",
    nameZh: "智学伴 · AI 智能学习平台",
    nameEn: "IntelliBuddy",
    status: "已上线",
    tagline: "集 AI 助教、交互式知识图谱、学习路径规划与数据看板于一体的智能助学平台。",
    liveUrl: "https://intellibuddy.luck007.online/",
    trackSlugs: ["ai", "software"],
    image: "/images/works/zhixueban/zhixueban-light.webp",
    logo: "/images/works/zhixueban/zhixueban-logo.webp",
    stackSummary: ["Vue 3", "TypeScript", "Express", "MongoDB", "AntV X6"],
    highlights: [
      "AntV X6 交互式知识拓扑图谱与先修依赖关系动态高亮",
      "大模型 SSE 双轨流式打字机响应与多轮上下文追问",
      "多模型容灾降级调度池与链路健康度自动嗅探",
      "全栈 TypeScript Monorepo 模块化架构与共享类型契约",
    ],
    detail: {
      problem: [
        "传统的网课或刷题网站大多是死板的线性目录列表，根本看不清知识点之间的先修依赖；而纯对话 AI 工具又太容易跑偏产生幻觉，聊着聊着就不知道学到哪儿了。",
        "智学伴把 AntV X6 知识拓扑图谱与大模型流式助教深度协同：左侧是像星图一样的交互式拓扑网络，右侧是带思维链与实时 LaTeX 渲染的流式助教，让学生既能宏观把握技术路线，又能针对具体疑难随时沉浸式答疑。",
      ],
      stack: {
        "前端应用": ["Vue 3", "TypeScript", "Vite", "AntV X6", "Pinia"],
        "服务端与模型": ["Node.js", "Express", "MongoDB", "SSE", "多模型调度池"],
        "工程与协作": ["pnpm Monorepo", "共享类型契约", "ESLint", "Prettier"],
      },
      principles: [
        {
          code: "GRAPH_01",
          name: "AntV X6 知识图谱拓扑空间与力导向物理引擎",
          category: "图谱渲染引擎",
          summary: "把 500+ 个概念做成带引力和斥力的力导向网络，先修与依赖关系一眼看清。",
          mechanism: "突破传统线性目录的死板展示。基于 AntV X6 构建知识点有向无环图（DAG），采用自适应电荷斥力与弹簧引力平衡解算节点空间坐标，支持视口平移缩放、正交智能避障连线与前置依赖路径动态点亮。",
          codeSnippet: `const graph = new Graph({\n  container: document.getElementById('knowledge-canvas'),\n  autoResize: true,\n  interacting: { nodeMovable: true },\n  connecting: { router: 'orth', connector: 'rounded' },\n});\n// 力导向拓扑空间自适应布局\ngraph.use(new ForceLayout({ charge: -160, linkDistance: 90 }));`,
          keyBenefit: "实现 500+ 学科概念节点的自适应拓扑布局与先修依赖秒级动态回溯",
          tags: ["AntV X6", "Knowledge Graph", "Force-Directed", "DAG Topology"],
        },
        {
          code: "STREAM_02",
          name: "Dual-Channel SSE 双轨流式通道与增量 AST 解析",
          category: "双轨流式架构",
          summary: "将大模型思维链（CoT）与正文分两条流下发，前端增量修补未闭合公式，消灭白屏与乱跳。",
          mechanism: "传统流式输出容易在遇到未闭合代码块或 LaTeX 公式时导致页面剧烈抖动。智学伴构建双轨 SSE 通道分流传输思考链与正文，前端增量 AST 补全器在字符流到达的同时进行未闭合标签修补与语法高亮，首字渲染时间（TTFT）压至 800ms 内。",
          codeSnippet: `// 双轨流式数据分发与增量 AST 补全\nsseSource.onmessage = (event) => {\n  const { channel, token } = JSON.parse(event.data);\n  if (channel === 'THOUGHT') thoughtStream.append(token);\n  else if (channel === 'CONTENT') incrementalMarkdownParser.feed(token);\n};`,
          keyBenefit: "首字响应延迟（TTFT）< 800ms，消除流式公式抖动，交互流畅度提升 60%",
          tags: ["Server-Sent Events", "AST Stream Parser", "Chain of Thought", "Incremental Render"],
        },
        {
          code: "FAILOVER_03",
          name: "Multi-LLM Failover Pool 多模型自适应容灾调度",
          category: "容灾调度机制",
          summary: "大模型 API 限流报错在所难免。调度池实时测速与嗅探，200ms 内无感切到备用模型。",
          mechanism: "面向高频多并发与不可靠上游大模型 API，构建自适应权重连接池。通过滑动时间窗口统计各提供商的延迟分位数、Token 速率与 429/500 报错率，遭遇熔断时毫秒级重试备用模型，保证知识问答服务 99.9% 稳定可用。",
          keyBenefit: "平均故障转移开销 < 200ms，保障学习会话 99.9% 高可用与无感容灾",
          tags: ["Multi-LLM", "Failover Pool", "Circuit Breaker", "Adaptive Load Balancing"],
        },
      ],
      architecture: {
        summary: "图谱引导与流式协同学习架构：从 AntV X6 拓扑空间到 SSE 流式网关、多模型容灾调度与 Monorepo 共享契约。",
        tiers: [
          {
            code: "TIER_01",
            name: "知识图谱与流式学习",
            role: "AntV X6 知识拓扑交互与增量 AST 打字机渲染",
            techTags: ["Vue 3", "TypeScript", "Vite", "AntV X6", "Pinia", "Tailwind CSS"],
            features: ["先修路径高亮", "力导向布局", "增量渲染"],
          },
          {
            code: "TIER_02",
            name: "实时网关与分发",
            role: "SSE 双轨流式通道与上下文滑动窗口管理",
            techTags: ["Server-Sent Events", "Node.js", "Express", "Token Stream Parser"],
            features: ["TTFT < 800ms", "多轮追问", "流式中断"],
          },
          {
            code: "TIER_03",
            name: "多模型容灾调度",
            role: "主备大模型 99.9% 自动故障转移与健康嗅探",
            techTags: ["Multi-LLM Failover Pool", "Prompt Engineering", "RBAC Auth"],
            features: ["99.9% 可用性", "知识库锚定", "分级权限"],
          },
          {
            code: "TIER_04",
            name: "持久化与 Monorepo",
            role: "MongoDB 轨迹存储与全栈 TS 共享数据契约",
            techTags: ["MongoDB", "pnpm Monorepo", "共享类型契约", "ESLint", "Prettier"],
            features: ["轨迹持久化", "跨端共享契约", "流水线保障"],
          },
        ],
        dataflow: [
          { step: "01", title: "图谱探索与路径高亮", detail: "点击概念节点回溯先修依赖", protocol: "Graph Event" },
          { step: "02", title: "带上下文 AI 提问", detail: "携带图谱锚点发起实时追问", protocol: "Context Payload" },
          { step: "03", title: "多模型容灾调度", detail: "遇限流毫秒级无缝切至备选池", protocol: "Failover Dispatch" },
          { step: "04", title: "SSE 双轨流式到达", detail: "增量 Markdown AST 逐字渲染", protocol: "Token Stream" },
          { step: "05", title: "学习轨迹归档", detail: "掌握度写入 MongoDB 并刷新报告", protocol: "Persistence" },
        ],
      },
      decisions: [
        {
          what: "基于 AntV X6 构建交互式知识先修依赖拓扑图谱",
          why: "打破传统线性目录死板结构，直观呈现网状依赖与先修前置约束，支持先修路径高亮与力导向排版。",
          tag: "GRAPH // 知识拓扑引擎",
          problem: "传统学习系统将知识点切分为扁平线性的章节列表，学习者无法直观认知不同概念之间的前置依赖关系，容易陷入“跳步学习导致理解断层”的困境。",
          solution: "采用 AntV X6 图编辑引擎定制知识拓扑网络：将概念建模为有向无环图（DAG），开发自定义节点高亮、先修路径正向/反向追溯与动态层级折叠算法。",
          impact: "实现了学习路径的全局可视化导航，知识点依赖清晰度提升 80%，支持从宏观图谱无缝下钻至微观 AI 对话。",
          tradeoff: "大节点量下力导向布局会消耗较多浏览器渲染算力，通过视口剔除（Viewport Culling）与层级懒加载进行性能优化。",
          highlight: "AntV X6 DAG Prerequisite Tracker",
        },
        {
          what: "大模型 SSE 双轨流式打字机管道与增量 AST 解析",
          why: "Token 级推理结果即时渲染，首字时间由数秒降至数百毫秒，显著降低长篇推导的等待焦虑。",
          tag: "STREAM // 流式交互管道",
          problem: "复杂代码编写与数学公式推导往往需要数千 Token 的生成时间，若采用传统阻塞式 HTTP 响应，用户需面对长达 5~15 秒的空白等待，交互体验极差。",
          solution: "全链路采用 Server-Sent Events (SSE) 协议，服务端逐 Token 推送；前端配合轻量级增量 Markdown AST 解析器实现边接收边高亮排版的打字机动效。",
          impact: "首字呈现时延（TTFT）压降至 800ms 以内，流式呈现流畅稳定，支持随时中断生成与快速追问。",
          tradeoff: "需在前端维护流式异常中断状态机与不完整 Markdown 闭合标签自动补全机制。",
          highlight: "SSE Token Pipeline + Incremental AST",
        },
        {
          what: "多模型自适应容灾降级调度池机制",
          why: "在上游主力模型接口出现限流（429）、超时或服务抖动时，毫秒级无缝降级至备用模型，保证服务高可用。",
          tag: "RESILIENCE // 模型容灾调度",
          problem: "第三方大模型服务商 API 普遍存在偶发性网络抖动、并发限流（Rate Limit 429）或突发宕机，单一模型依赖会导致平台核心助教功能频繁中断。",
          solution: "在 Node.js 服务层构建多模型调度池：设立主力与备选模型权重梯队，集成心跳熔断器（Circuit Breaker），捕获异常后毫秒级无缝自动重试并切换降级线路。",
          impact: "将 AI 助教服务的整体可用性提升至 99.9% 以上，彻底杜绝单点 API 故障导致的用户对话失败。",
          tradeoff: "不同模型之间的 System Prompt 表达与输出格式存在细微差异，需在调度层对返回 payload 做统一格式规范化抹平。",
          highlight: "Adaptive LLM Failover Pool",
        },
        {
          what: "TypeScript 全栈 Monorepo 模块化架构与共享契约",
          why: "前后端共享数据契约接口与通用工具库，降低跨模块协作中的版本脱节风险。",
          tag: "ARCH // 全栈类型闭环",
          problem: "传统前后端独立仓库开发常导致前端与服务端类型定义脱节，修改字段时缺乏全局类型检查，接口契约变动极易引发隐蔽的线上运行时错误。",
          solution: "基于 pnpm Workspace 搭建全栈 TypeScript Monorepo：抽取共享类型定义包统一管理所有 DTO、图谱节点模型与 API 响应结构。",
          impact: "实现前后端 100% 类型同构共享与编译期静态检查，重构与字段演进安全可靠。",
          tradeoff: "要求开发人员具备全栈 TypeScript 工程素养，并在 CI 流程中配置多包增量构建与缓存策略。",
          highlight: "pnpm Workspace + Shared DTO Package",
        },
      ],
      metrics: [
        { label: "知识图谱交互", value: "AntV X6 拓扑", tag: "TOPOLOGY-NAV", status: "verified", progress: 95, description: "支持网状有向图拓扑渲染、先修路径反向追踪与力导向排版" },
        { label: "流式首字时延", value: "TTFT < 800ms", tag: "STREAM-PIPELINE", status: "realtime", progress: 92, description: "SSE 双轨流式通道结合增量 AST，实现逐 Token 毫秒级打字机响应" },
        { label: "模型可用性保障", value: "99.9% 容灾调度", tag: "MULTI-LLM-POOL", status: "hardened", progress: 99, description: "主备模型池自适应故障转移与熔断探测，抵御第三方 API 限流抖动" },
        { label: "全栈架构模式", value: "TS Monorepo", tag: "FULLSTACK-TS", status: "verified", progress: 100, description: "前后端统一 TypeScript 类型定义、共享数据契约与统一构建门禁" },
      ],
      tradeoffs: [
        {
          title: "图谱结构化导航优先于自由生成",
          detail: "坚持以权威知识库作为图谱锚点，AI 对话紧密挂载于具体节点上下文，避免大语言模型在无约束发散中产生知识幻觉。",
        },
        {
          title: "多角色空间与渐进式功能分级",
          detail: "系统设计了普通学生、高级学员到教师端的 RBAC 权限体系，将练习测验、学习报告与管理面板进行分级隔离与清晰授权。",
        },
      ],
      demoAccounts: [
        { role: "普通学生", account: "student@intellibuddy.com", password: "Demo2025", access: "日常学习、AI 助教、测验系统" },
        { role: "高级学生", account: "advanced@intellibuddy.com", password: "Demo2025", access: "数据分析、成就系统、学习报告" },
        { role: "VIP 会员", account: "vip@intellibuddy.com", password: "Demo2025", access: "完整功能体验；会员特权、积分商城为后续方向" },
        { role: "教师", account: "teacher@intellibuddy.com", password: "Demo2025", access: "教师功能体验；班级管理、作业布置为后续方向" },
        { role: "新用户", account: "newuser@intellibuddy.com", password: "Demo2025", access: "新手引导、从零开始体验" },
      ],
      shots: {
        type: "comparison",
        dark: "/images/works/zhixueban/zhixueban-dark.webp",
        light: "/images/works/zhixueban/zhixueban-light.webp",
        alt: "智学伴 AI 智能学习平台明暗主题主页",
      },
      gallery: [
        {
          label: "AI 智能助教",
          description: "通过流式对话承接学习问题，并保留连续追问的上下文。",
          shot: { type: "single", image: "/images/works/zhixueban/zhixueban-ai-chat.webp", alt: "智学伴 AI 智能助教对话界面" },
        },
        {
          label: "知识图谱与路线",
          description: "用交互节点呈现知识点依赖关系和阶段学习路线。",
          shot: { type: "single", image: "/images/works/zhixueban/zhixueban-roadmap.webp", alt: "智学伴 AntV X6 知识图谱与学习路线界面" },
        },
        {
          label: "知识库阅读",
          description: "将结构化正文与图谱节点连接，支持从关系视图回到具体内容。",
          shot: { type: "single", image: "/images/works/zhixueban/zhixueban-knowledge.webp", alt: "智学伴知识库正文阅读界面" },
        },
        {
          label: "登录认证",
          description: "独立认证入口承接用户身份与个人学习空间。",
          shot: { type: "single", image: "/images/works/zhixueban/zhixueban-login.webp", alt: "智学伴平台登录认证界面" },
        },
      ],
    },
  },
  {
    slug: "resistor-inspection",
    nameZh: "电阻片电压智能检测与码垛系统",
    status: "在研",
    tagline: "面向工业产线电阻片精密检测场景，使用工业相机识别特征圆心坐标，联动机械臂完成高精抓取、分拣与多工位码垛验证。",
    trackSlugs: ["ai", "industrial"],
    stackSummary: ["机器视觉", "工业相机", "机械臂"],
    highlights: [
      "工业级双目定位与亚毫米级圆心坐标提取算法",
      "六轴机械臂动态轨迹规划与气动吸附多工位码垛",
      "端侧嵌入式工控机与 PLC 实时工业通信闭环联调",
    ],
  },
  {
    slug: "pv-defect-detection",
    nameZh: "无人机光伏板缺陷检测系统",
    status: "在研",
    tagline: "基于 YOLOv9 与无人机高空航拍图像，实现对集中式光伏电站组件热斑、隐裂与异物遮挡的大规模自主智能巡检。",
    trackSlugs: ["ai", "industrial"],
    stackSummary: ["YOLOv9", "无人机巡检", "目标检测"],
    highlights: [
      "红外热成像与可见光航拍多波段多尺度特征融合",
      "微小局部热斑、物理隐裂与异物遮挡多标签检测",
      "针对机载边缘计算设备的轻量化模型蒸馏加速",
    ],
  },
  {
    slug: "oral-infection-control",
    nameZh: "口腔感控设备辅助系统",
    status: "在研",
    tagline: "结合物联网多维时序传感与医疗器械消毒监测，构建符合卫监规范的口腔诊疗器械全生命周期数字化追踪管理流程。",
    trackSlugs: ["cloud-iot", "industrial"],
    stackSummary: ["物联网感知", "设备监测", "外部管理"],
    highlights: [
      "高温高压灭菌全流程温湿度与压力时序数据采集",
      "多协议传感器边缘网关接入与运行异常瞬时告警",
      "清洗消毒包装至发放全生命周期追溯合规数字化报表",
    ],
  },
] satisfies Work[];
